### PR TITLE
WIP: revise problem descriptions

### PR DESCRIPTION
**Pull request by jbcaillau**
@ocots @BaptisteCbl hi guys, would be nice to revise the descriptions taking into account the new API (variable, essentially) both for functional and abstract formulations. I've just updated the double integrator, min time, in this PR. To be continued. Doing so will generate a nice series of tests (functional / abstract).

PS. Do we really need to keep two versions of Goddard problem?

### CODE REVIEW

**Comment by ocots** [comment]
- We intended to update the descriptions of the models. However, we need before to update `CTFlows` considering the version `0.7` of `CTBase`.
- Then, to take into account this new versions of `CTFlows`and `CTBase` here, we need to update the `[compat]` section of the `Project.toml` file.
- For Goddard problem, it was to have a problem with all the different types of constraints but now with all the problems we have, I think we can remove the second version of Goddard. Are you ok @PierreMartinon ?

**Comment by ocots** [comment]
@BaptisteCbl I have updated some tests in `transit` branch. To continue.

**Comment by ocots** [comment]
Move to other PR.

**Comment by jbcaillau** [comment]
@ocots @jbcaillau also some stuff to update in `OptimalControl`. I have started [this PR](https://github.com/control-toolbox/OptimalControl.jl/pull/138).

**Pull request closed without merging**
